name = "disarm-club-game"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = ""
route = ""
zone_id = ""
compatibility_date = "2021-10-10"

[build]
command = "npm ci && npm run build"
[build.upload]
dir = "src"
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{ name = "DISARM_CLUB_GAME", class_name = "DisarmClubGame" }]

[[migrations]]
tag = "v1"
new_classes = ["DisarmClubGame"]
